export {default as DashBoardPage} from './Dashboard.page'
export {default as SalePage} from './Sale.page'
export {default as VoucherPage} from './Voucher.page'
export {default as NotFoundPage} from './NotFound.page'
export {default as ProductPage} from './Product.page'
export {default as ProductDetailPage} from './ProductDetail.page'